// Re-export generated token constants and CSS variable references
// These files are auto-generated by Style Dictionary — see sd.config.ts

export { tokens } from './generated/tokens';
export type { DesignTokens } from './generated/tokens';
export { cssVars } from './generated/css-vars';
export type { CSSVarKey } from './generated/css-vars';

// Re-export raw JSON token sources for tools that need them
export { default as colorTokens } from './colors.json';
export { default as typographyTokens } from './typography.json';
export { default as spacingTokens } from './spacing.json';
export { default as radiusTokens } from './radius.json';
export { default as shadowTokens } from './shadows.json';
export { default as motionTokens } from './motion.json';
export { default as opacityTokens } from './opacity.json';
export { default as zIndexTokens } from './z-index.json';
export { default as breakpointTokens } from './breakpoints.json';
