import StyleDictionary from 'style-dictionary';

// ─────────────────────────────────────────────
// Custom format: CSS Variables
// ─────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'css/custom-variables',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => {
      const name = token.path.join('-');
      return `  --ds-${name}: ${token.value};`;
    });
    return `/* Auto-generated by Style Dictionary — DO NOT EDIT */\n:root {\n${lines.join('\n')}\n}\n`;
  },
});

// ─────────────────────────────────────────────
// Custom format: TypeScript constants
// ─────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'typescript/constants',
  format: ({ dictionary }) => {
    const buildObj = (tokens: typeof dictionary.allTokens): string => {
      const result: Record<string, unknown> = {};

      for (const token of tokens) {
        let current = result;
        for (let i = 0; i < token.path.length - 1; i++) {
          const key = token.path[i]!;
          if (!(key in current)) {
            current[key] = {};
          }
          current = current[key] as Record<string, unknown>;
        }
        const lastKey = token.path[token.path.length - 1]!;
        current[lastKey] = token.value;
      }

      return JSON.stringify(result, null, 2);
    };

    return `/* Auto-generated by Style Dictionary — DO NOT EDIT */\nexport const tokens = ${buildObj(dictionary.allTokens)} as const;\n\nexport type DesignTokens = typeof tokens;\n`;
  },
});

// ─────────────────────────────────────────────
// Custom format: CSS Variable references for TS
// ─────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'typescript/css-vars',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => {
      const name = token.path.join('-');
      const key = token.path.join('.');
      return `  '${key}': 'var(--ds-${name})',`;
    });
    return `/* Auto-generated by Style Dictionary — DO NOT EDIT */\nexport const cssVars = {\n${lines.join('\n')}\n} as const;\n\nexport type CSSVarKey = keyof typeof cssVars;\n`;
  },
});

// ─────────────────────────────────────────────
// Build Configuration
// ─────────────────────────────────────────────
async function build() {
  const sd = new StyleDictionary({
    source: ['src/tokens/*.json'],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'src/tokens/build/',
        files: [
          {
            destination: 'variables.css',
            format: 'css/custom-variables',
          },
        ],
      },
      ts: {
        transformGroup: 'js',
        buildPath: 'src/tokens/generated/',
        files: [
          {
            destination: 'tokens.ts',
            format: 'typescript/constants',
          },
          {
            destination: 'css-vars.ts',
            format: 'typescript/css-vars',
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  console.log('✅ Design tokens built successfully!');
}

build().catch((err) => {
  console.error('❌ Token build failed:', err);
  process.exit(1);
});
